In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

In [3]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-22 19:12:29--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv’

car_fuel_efficiency 100%[===================>] 620.29K  --.-KB/s    in 0.03s   

2026-09-22 19:12:29 (19.6 MB/s) - ‘car_fuel_efficiency_2026.csv’ saved [635180/635180]



In [4]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [6]:
len(df)

10000

In [7]:
df.shape

(10000, 11)

In [8]:
df.fuel_type.nunique()

3

In [9]:
df.fuel_type.unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [11]:
(df.isnull().sum() > 0).sum()

np.int64(2)

In [12]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

np.float64(41.2)

In [15]:
df.horsepower.median()

np.float64(254.0)

In [16]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [17]:
mode_hp = df.horsepower.mode()[0]
mode_hp

np.float64(252.0)

In [18]:
df.horsepower = df.horsepower.fillna(mode_hp)

In [19]:
df.horsepower.isnull().sum()

np.int64(0)

In [20]:
df.horsepower.median()

np.float64(252.0)

In [21]:
df_asia = df[df.origin == 'Asia']

X = df_asia[['vehicle_weight', 'model_year']].head(7).values

X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [22]:
X.shape

(7, 2)

In [23]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [24]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [25]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [26]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [27]:
w.sum()

np.float64(0.36919696904925486)